#server:
#  port: 8081
#spring:
#  zipkin:
#    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#  application:
#    name: service-product
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql:///shop? serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: 123456
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#service-product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule